#!/usr/bin/env sh

alias ..='cd ..'
alias ...='cd ../..'
alias dev='cd $HOME/dev'

# Long view and show hidden
alias ll='ls -lahF'

# Manage .my-conf git files
alias conf='/usr/bin/git --git-dir=$HOME/.my-conf/ --work-tree=$HOME'

alias e='emacsclient --tty'

alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -out'
