#!/usr/bin/env sh

export LANG=en_US.UTF-8

#
# Colors
#

RED="\[\033[0;31m\]"
PINK="\[\033[1;31m\]"
YELLOW="\[\033[1;33m\]"
GREEN="\[\033[0;32m\]"
LT_GREEN="\[\033[1;32m\]"
BLUE="\[\033[0;34m\]"
WHITE="\[\033[1;37m\]"
PURPLE="\[\033[1;35m\]"
CYAN="\[\033[1;36m\]"
BROWN="\[\033[0;33m\]"
COLOR_NONE="\[\033[0m\]"

export CLICOLOR=1

# Documentation about ls colors:
# http://linux-sxs.org/housekeeping/lscolors.html
export LSCOLORS=GxFxCxDxBxegedabagaced

export GREP_COLOR='1;31'

export TERM=xterm-256color

#
# History
#

# Ignore duplicate entries in history
export HISTCONTROL=erasedups:ignoreboth
export HISTFILE=~/.zsh_history
# Increases size of history
export HISTSIZE=10000
export SAVEHIST=10000
export HISTIGNORE="&:ls:ll:la:l.:pwd:exit:clear:clr:[bf]g"
