- name: Install system dependencies
  become: yes
  become_user: root
  tags:
    - deps
  apt:
    pkg:
      # Required by: rbenv
      - zlib1g-dev

- name: Clone rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: "{{ lookup('env', 'HOME') }}/.rbenv"

# Simplify the installation of new ruby versions using `rbenv
# install`.
- name: Clone rbenv ruby-build plugin
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: "{{ lookup('env', 'HOME') }}/.rbenv/plugins/ruby-build"

- name: Add ~/.rbenv/bin to PATH
  lineinfile:
    path: "{{ zshenv }}"
    create: yes
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'

- name: Add rbenv init eval
  lineinfile:
    path: "{{ zshenv }}"
    create: yes
    line: 'eval "$(rbenv init -)"'

- name: Install Ruby 2.6.5
  # Source the .zshenv file before execute the rbenv in the current session.
  # See https://stackoverflow.com/a/27541856
  shell: ". {{ zshenv }} && rbenv install 2.6.5"
