- name: Install system dependencies
  become: yes
  become_user: root
  tags:
    - deps
  apt:
    pkg:
      # Required by: rbenv
      # rbenv requires a C compiler to install any ruby version.
      - build-essential

      # Required by: rbenv
      - zlib1g-dev
      - libssl-dev
      - libreadline-dev

- name: Clone rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: "{{ lookup('env', 'HOME') }}/.rbenv"

# Simplify the installation of new ruby versions using `rbenv
# install`.
- name: Clone rbenv ruby-build plugin
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: "{{ lookup('env', 'HOME') }}/.rbenv/plugins/ruby-build"

- name: Add ~/.rbenv/bin to PATH
  lineinfile:
    path: "{{ zshenv }}"
    create: yes
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'

- name: Add rbenv init eval
  lineinfile:
    path: "{{ zshenv }}"
    create: yes
    line: 'eval "$(rbenv init -)"'

- name: "Install Ruby {{ ruby_version }}"
  # Source the .zshenv file before execute the rbenv in the current session.
  # See https://stackoverflow.com/a/27541856
  shell: ". {{ zshenv }} && rbenv install {{ ruby_version }}"

- name: "Set Ruby {{ ruby_version }} as global"
  shell: ". {{ zshenv }} && rbenv global {{ ruby_version }}"

- name: Install Bundler gem
  shell: ". {{ zshenv }} && gem install bundler"

- name: Install Pry gem
  shell: ". {{ zshenv }} && gem install pry"

- name: Create ~/.irbrc file
  become: yes
  become_user: root
  file:
    path: "{{ lookup('env', 'HOME') }}/.irbrc"
    state: touch
    force: yes

- name: Add Pry.start in the ~/.irbrc
  blockinfile:
    path: "{{ lookup('env', 'HOME') }}/.irbrc"
    block: |
      require 'pry'
      Pry.start
      exit
