- name: Install system packages
  become: yes
  become_user: root
  apt:
    pkg:
      - build-essential
      - git
      - curl
      - xclip
      - htop
      - exuberant-ctags
      - libreadline-dev
      - libssl-dev
      - silversearcher-ag
      - tig
      - jq
      - fd-find

- name: Create shell/aliases link
  file:
    src: "{{ lookup('env', 'DOTFILES_DIR') }}/shell/aliases"
    dest: "{{ lookup('env', 'HOME') }}/aliases"
    state: link
    force: yes

- name: Create shell/vars link
  file:
    src: "{{ lookup('env', 'DOTFILES_DIR') }}/shell/vars"
    dest: "{{ lookup('env', 'HOME') }}/vars"
    state: link
    force: yes


# The .composed-variables purpose is store variables and
# configurations create dynamically during Ansible tasks. Therefore,
# it shouldn't be versioned.
#
# This file is sourced in the `.zshrc`.
- name: Create ~/.composed-variables file
  file:
    path: "{{ lookup('env', 'HOME') }}/.composed-variables"
    state: touch

- name: Create ~/.local/bin directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: directory

#
# fzf
#

- name: Clone fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    depth: 1
    dest: "{{ lookup('env', 'HOME') }}/.fzf"

- name: Install fzf
  command: "{{ lookup('env', 'HOME') }}/.fzf/install"

- name: Set FZF_DEFAULT_OPTS
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.composed-variables"
    regexp: '^export FZF_DEFAULT_OPTS='
    line: "export FZF_DEFAULT_OPTS='--layout=reverse --border --inline-info'"

#
# Git
#

- name: Create .gitconfig link
  file:
    src: "{{ lookup('env', 'DOTFILES_DIR') }}/.gitconfig"
    dest: "{{ lookup('env', 'HOME') }}/.gitconfig"
    state: link
    force: yes
