- name: Install zprezto
  git:
    repo: https://github.com/sorin-ionescu/prezto.git
    dest: "{{ lookup('env', 'HOME') }}/.zprezto"
    recursive: true

- name: Create .zpreztorc link
  file:
    src: "{{ lookup('env', 'DOTFILES_DIR') }}/.zpreztorc"
    dest: "{{ lookup('env', 'HOME') }}/.zpreztorc"
    state: link
    force: yes
