- name: Get latest stable version
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/stable.txt
    dest: /tmp/kubernetes-stable.txt
  tags: [ kubernetes ]

- name: Register latest version
  shell: cat /tmp/kubernetes-stable.txt
  register: kubernetes_stable
  tags: [ kubernetes ]

- name: Ensure ~/.local/bin exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: directory
  tags: [ kubernetes ]

- name: Install kubectl
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubernetes_stable.stdout }}/bin/linux/amd64/kubectl"
    dest: "{{ lookup('env', 'HOME') }}/.local/bin/kubectl"
    mode: "+x"
  tags: [ kubernetes ]
