- name: Install Slack with --classic option
  snap:
    name: slack
    classic: yes

- name: Install Spotify
  snap:
    name: spotify

- name: Install Insomnia HTTP and GraphQL client
  snap:
    name: insomnia

- name: Install Google Chrome
  become: yes
  become_user: root
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

- name: Install lastpass-cli
  become: yes
  become_user: root
  apt:
    name: lastpass-cli
