# Keychron K2 Ubuntu settings
# See https://github.com/Kurgol/keychron/blob/master/k2.md#f-keys-on-ubuntu
- name: Create /etc/modprobe.d/hid_apple.conf file
  become: yes
  become_user: root
  file:
    path: "/etc/modprobe.d/hid_apple.conf"
    state: touch
    force: no

- name: Enable fnmode=2 to lock F keys
  become: yes
  become_user: root
  lineinfile:
    path: "/etc/modprobe.d/hid_apple.conf"
    create: yes
    regexp: "options hid_apple fnmode=2"
    line: "options hid_apple fnmode=2"

# NOTE: It require a reboot to work.
- name: Update all existing initramfs
  become: yes
  become_user: root
  shell: update-initramfs -u
