- name: Install tmux
  become: yes
  become_user: root
  apt:
    name: tmux
    state: present

- name: Create .tmux.conf link
  file:
    src: "{{ lookup('env', 'DOTFILES_DIR') }}/.tmux.conf"
    dest: "{{ lookup('env', 'HOME') }}/.tmux.conf"
    state: link
    force: yes
