#!/usr/bin/env sh

alias ..='cd ..'
alias ...='cd ../..'
alias dev='cd $HOME/dev'

# Long view and show hidden
alias ll='ls -lahF'

# Disk free, in gigabytes, not bytes
alias df='df -h'

# Calculate total disk usage for a folder
alias du='du -hc'

# Manage .my-conf git files
alias conf='/usr/bin/git --git-dir=$HOME/.my-conf/ --work-tree=$HOME'

# Launch Spotify with UI scale of 150% in background
alias spotify='spotify --force-device-scale-factor=1.5 &>/dev/null &'

alias e='emacsclient --tty'
alias e-force-exit="kill -9 $(ps aux | grep '[e]macs --daemon' | awk '{print $2}')"

alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -out'
