#!/usr/bin/env sh

alias ..='cd ..'
alias ...='cd ../..'
alias dev='cd $HOME/dev'

# Long view and show hidden
alias ll='ls -lahF'

# Disk free, in gigabytes, not bytes
alias df='df -h'

# Calculate total disk usage for a folder
alias du='du -hc'

# Manage .my-conf git files
alias conf='/usr/bin/git --git-dir=$HOME/.my-conf/ --work-tree=$HOME'

if [[ "$(uname --kernel-name)" = "Linux" ]]; then
  alias pbcopy='xclip -selection clipboard'
  alias pbpaste='xclip -selection clipboard -out'
fi
