#!/usr/bin/env bash

clone_dotfiles () {
  if [[ ! -d "$HOME/dev/dotfiles" ]]; then
    mkdir -p $HOME/dev
    git clone git@github.com:ilmotta/dotfiles.git $HOME/dev/dotfiles
  else
    echo "~> dotfiles repository already cloned."
  fi
}

create_symlinks_to_dotfiles () {
  local dotfiles_path=$HOME/dev/dotfiles

  ln -sf $dotfiles_path/.vim        $HOME
  ln -sf $dotfiles_path/.vimrc      $HOME
  ln -sf $dotfiles_path/.shell      $HOME
  ln -sf $dotfiles_path/.vscode     $HOME
  ln -sf $dotfiles_path/.zshrc      $HOME
  ln -sf $dotfiles_path/.zpreztorc  $HOME
  ln -sf $dotfiles_path/.gitconfig  $HOME
  ln -sf $dotfiles_path/.gitignore  $HOME
  ln -sf $dotfiles_path/.tmux.conf  $HOME
  ln -sf $dotfiles_path/.iterm      $HOME
}

install_tmux_plugin_manager () {
  if [[ ! -d "$HOME/.tmux" ]]; then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  else
    echo "~> tmux plugin manager found. Skipping installation."
  fi
}

install_node_version_manager () {
  if [[ -d "$HOME/.nvm" ]]; then
    echo "~> nvm found. Skipping installation."
  else
    git clone https://github.com/creationix/nvm.git $HOME/.nvm
  fi
}

install_vim_plugin_manager () {
  if [[ ! -f "$HOME/.vim/autoload/plug.vim" ]]; then
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  else
    echo "~> vim-plug found. Skipping installation."
  fi
}

install_zprezto () {
  if [[ ! -d "$HOME/.zprezto" ]]; then
    echo "~> Installing zprezto..."
    git clone --recursive https://github.com/sorin-ionescu/prezto.git $HOME/.zprezto
  else
    echo "~> zprezto found. Skipping installation."
  fi
}

install_vscode_extensions () {
  cat $HOME/.vscode/extensions.txt | xargs -L 1 code --install-extension
}
