#!/usr/bin/env bash

setup_gnome () {
  # Modify capslock to be ctrl. Also, set compose key to print screen in order
  # to write special characters in a US keyboard (requires gnome-tweak-tool)
  gsettings set org.gnome.desktop.input-sources xkb-options "['ctrl:nocaps', 'compose:ralt']"

  gsettings set org.gnome.desktop.peripherals.keyboard delay 200
  gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 30

  gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark
  gsettings set org.gnome.desktop.interface show-battery-percentage true
  gsettings set org.gnome.desktop.interface clock-format 12h
  gsettings set org.gnome.desktop.interface clock-show-weekday true
  gsettings set org.gnome.desktop.interface clock-show-date true

  gsettings set org.gnome.shell.extensions.dash-to-dock dock-position BOTTOM
  gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 32
  gsettings set org.gnome.shell.extensions.dash-to-dock autohide true
}

setup_gnome_terminal_base16_solarized_profile () {
  git clone https://github.com/chriskempson/base16-gnome-terminal.git /tmp/base16-gnome-terminal
  source /tmp/base16-gnome-terminal/base16-solarized.dark.sh
}

install_basic_dependencies () {
  sudo apt-get update
  sudo apt-get install --yes \
    build-essential \
    git \
    curl \
    xclip \
    htop \
    exuberant-ctags \
    libreadline-dev \
    libssl-dev \
    openjdk-8-jdk \
    silversearcher-ag \
    tig \
    zsh \
    vim-gnome \
    tmux \
    gopass \
    nodejs \
    telegram-desktop \
    gnome-tweak-tool
}

# After installation, log out and log in for the group changes to take effect.
install_docker () {
  which docker &> /dev/null
  if [[ $? != 0 ]]; then
    sudo apt-key adv \
      --keyserver hkp://ha.pool.sks-keyservers.net:80 \
      --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

    echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" \
      | sudo tee /etc/apt/sources.list.d/docker.list

    sudo apt-get install --yes \
      linux-image-extra-$(uname -r) linux-image-extra-virtual \
      apt-transport-https ca-certificates

    sudo apt-get install --yes docker-engine docker-compose
    sudo gpasswd -a ${USER} docker
  else
    echo "~> docker found. Skipping installation"
  fi
}

install_docker_compose () {
  which docker-compose &> /dev/null
  if [[ $? != 0 ]]; then
    sudo curl \
      -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-`uname -s`-`uname -m` \
      -o /usr/local/bin/docker-compose

    sudo chmod +x /usr/local/bin/docker-compose
  else
    echo "~> docker-compose found. Skipping installation"
  fi

}

install_npm () {
  which npm &> /dev/null
  if [[ $? != 0 ]]; then
    sudo apt-get install --yes npm
  else
    echo "~> npm found. Skipping installation"
  fi
}

install_google_chrome () {
  which google-chrome &> /dev/null
  if [[ $? != 0 ]]; then
    wget --output-document /tmp/google-chrome.deb \
      https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
      && sudo dpkg --install /tmp/google-chrome.deb
  else
    echo "~> google-chrome found. Skipping installation"
  fi
}

# Required by vim fzf plugin (see .vim/initializers/fzf.vim)
install_ripgrep () {
  which rg &> /dev/null
  if [[ $? != 0 ]]; then
    wget --output-document /tmp/ripgrep.deb \
      https://github.com/BurntSushi/ripgrep/releases/download/0.10.0/ripgrep_0.10.0_amd64.deb \
      && sudo dpkg --install /tmp/ripgrep.deb
  else
    echo "~> ripgrep found. Skipping installation"
  fi
}
