#!/usr/bin/env bash

setup_gnome () {
  # Modify capslock to be ctrl. Also, set compose key to print screen in order
  # to write special characters in a US keyboard (requires gnome-tweak-tool)
  gsettings set org.gnome.desktop.input-sources xkb-options "['ctrl:nocaps', 'compose:ralt']"

  gsettings set org.gnome.desktop.peripherals.keyboard delay 200
  gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 30

  gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark
  gsettings set org.gnome.desktop.interface show-battery-percentage true
  gsettings set org.gnome.desktop.interface clock-format 12h
  gsettings set org.gnome.desktop.interface clock-show-weekday true
  gsettings set org.gnome.desktop.interface clock-show-date true

  gsettings set org.gnome.shell.extensions.dash-to-dock dock-position BOTTOM
  gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 32
  gsettings set org.gnome.shell.extensions.dash-to-dock autohide true
}

setup_gnome_terminal_base16_solarized_profile () {
  git clone https://github.com/chriskempson/base16-gnome-terminal.git /tmp/base16-gnome-terminal
  source /tmp/base16-gnome-terminal/base16-solarized.dark.sh
}

install_basic_dependencies () {
  sudo apt-get update
  sudo apt-get install --yes \
    build-essential \
    git \
    curl \
    xclip \
    htop \
    exuberant-ctags \
    libreadline-dev \
    libssl-dev \
    openjdk-8-jdk \
    silversearcher-ag \
    tig \
    zsh \
    vim-gnome \
    tmux \
    gopass \
    nodejs \
    gnome-tweak-tool \
    jq
}

# After installation, log out and log in for the group changes to take effect.
install_docker () {
  which docker &> /dev/null
  if [[ $? != 0 ]]; then
    sudo apt-key adv \
      --keyserver hkp://ha.pool.sks-keyservers.net:80 \
      --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

    echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" \
      | sudo tee /etc/apt/sources.list.d/docker.list

    sudo apt-get install --yes \
      linux-image-extra-$(uname -r) linux-image-extra-virtual \
      apt-transport-https ca-certificates

    sudo apt-get install --yes docker-engine docker-compose
    sudo gpasswd -a ${USER} docker
  else
    echo "~> docker found. Skipping installation"
  fi
}

install_docker_compose () {
  which docker-compose &> /dev/null
  if [[ $? != 0 ]]; then
    sudo curl \
      -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-`uname -s`-`uname -m` \
      -o /usr/local/bin/docker-compose

    sudo chmod +x /usr/local/bin/docker-compose
  else
    echo "~> docker-compose found. Skipping installation"
  fi

}

install_npm () {
  which npm &> /dev/null
  if [[ $? != 0 ]]; then
    sudo apt-get install --yes npm
  else
    echo "~> npm found. Skipping installation"
  fi
}

install_yarn () {
  which yarn &> /dev/null
  if [[ $? != 0 ]]; then
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    sudo apt update && sudo apt install --yes yarn
  else
    echo "~> yarn found. Skipping installation"
  fi
}

install_google_chrome () {
  which google-chrome &> /dev/null
  if [[ $? != 0 ]]; then
    wget --output-document /tmp/google-chrome.deb \
      https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
      && sudo dpkg --install /tmp/google-chrome.deb
  else
    echo "~> google-chrome found. Skipping installation"
  fi
}

# Required by vim fzf plugin (see .vim/initializers/fzf.vim)
install_ripgrep () {
  which rg &> /dev/null
  if [[ $? != 0 ]]; then
    wget --output-document /tmp/ripgrep.deb \
      https://github.com/BurntSushi/ripgrep/releases/download/0.10.0/ripgrep_0.10.0_amd64.deb \
      && sudo dpkg --install /tmp/ripgrep.deb
  else
    echo "~> ripgrep found. Skipping installation"
  fi
}

install_gnome_terminal_zenburn_color () {
  sudo apt install dconf-cli

  if [[ ! -e "/tmp/gnome-terminal-colors" ]]; then
    git clone https://github.com/gnumoksha/gnome-terminal-colors.git /tmp/gnome-terminal-colors
  fi

  CURRENT_PROFILE=$(gsettings get org.gnome.Terminal.ProfilesList default | tr -d \')

  /tmp/gnome-terminal-colors/install.sh \
    --profile $(echo $CURRENT_PROFILE) \
    --scheme zenburn \
    --skip-dircolors
}

install_emacs () {
  which emacs &> /dev/null
  if [[ $? != 0 ]]; then
    sudo add-apt-repository ppa:kelleyk/emacs
    sudo apt-get update
    sudo apt install --yes emacs26
  else
    echo "~> emacs found. Skipping installation"
  fi
}

# TODO: Call fn in setup.sh
install_clojure_lein () {
  which lein &> /dev/null
  if [[ $? != 0 ]]; then
    local url=https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
    local lein_path=$HOME/.local/bin/lein
    mkdir -p $HOME/.local/bin

    curl $url --output $lein_path \
      && chmod +x $lein_path \
      && lein -v
  else
    echo "~> lein found. Skipping installation"
  fi
}


install_snapcraft () {
  which snap &> /dev/null
  if [[ $? != 0 ]]; then
    sudo add-apt-repository ppa:snappy-dev/tools
    sudo apt update
    sudo apt install --yes snapcraft
  else
    echo "~> snapcraft found. Skipping installation"
  fi
}


# TODO: Call fn in setup.sh
install_utility_apps () {
  sudo snap install spotify
  sudo snap install slack --classic
  sudo snap install telegram-desktop
  sudo snap install pats-boostnote --edge
  sudo snap install postman
  sudo snap install gimp
  sudo snap install vscode --classic
}

install_zoom () {
  which zoom &> /dev/null
  if [[ $? != 0 ]]; then
    local package_name=zoom_amd64.deb
    local url=https://zoom.us/client/latest/$package_name
    cd /tmp
    wget $url
    sudo apt-get install -y libxcb-xtest0
    sudo dpkg -i $package_name
    sudo apt-get -f install
    rm -f $package_name
  else
    echo "zoom already installed."
  fi
}

install_fzf () {
  which fzf &> /dev/null
  if [[ $? != 0 ]]; then
    git clone --depth 1 https://github.com/junegunn/fzf.git $HOME/.fzf
    $HOME/.fzf/install
  else
    echo "~> fzf found. Skipping installation"
  fi
}
