#!/usr/bin/env sh

export LANG=en_US.UTF-8

export BROWSER=google-chrome

export PATH="/usr/local/sbin:$HOME/.local/bin:$(yarn global bin):$PATH"

export NVM_DIR="$HOME/.nvm"

# Editor to fallback to if the server is not running
# If EDITOR is the empty string, start Emacs in daemon
# mode and try connecting again.
export ALTERNATE_EDITOR=""
export EDITOR="emacsclient --tty"

# Fix hide cursor bug when moving back along
# Reference:
# - https://github.com/zsh-users/zsh-syntax-highlighting/issues/171
# - https://github.com/howardcochran/hcc-dotfiles/commit/23a1b97ba7fffe0013ecde497f3f2cc1f3910795
export ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)

export FZF_DEFAULT_OPTS='--layout=reverse --border --inline-info'

# Colors {
  RED="\[\033[0;31m\]"
  PINK="\[\033[1;31m\]"
  YELLOW="\[\033[1;33m\]"
  GREEN="\[\033[0;32m\]"
  LT_GREEN="\[\033[1;32m\]"
  BLUE="\[\033[0;34m\]"
  WHITE="\[\033[1;37m\]"
  PURPLE="\[\033[1;35m\]"
  CYAN="\[\033[1;36m\]"
  BROWN="\[\033[0;33m\]"
  COLOR_NONE="\[\033[0m\]"

  export CLICOLOR=1

  # Documentation about ls colors:
  # http://linux-sxs.org/housekeeping/lscolors.html
  export LSCOLORS=GxFxCxDxBxegedabagaced

  export GREP_COLOR='1;31'

  export TERM=xterm-256color
# }

# History {
  export HISTCONTROL=erasedups:ignoreboth # Ignore duplicate entries in history
  export HISTFILE=~/.zsh_history
  export HISTSIZE=10000 # Increases size of history
  export SAVEHIST=10000
  export HISTIGNORE="&:ls:ll:la:l.:pwd:exit:clear:clr:[bf]g"
# }

