- name: Install iTerm2
  homebrew_cask:
    name: iterm2
    state: present

- name: Create .zshrc link
  file:
    src: "{{ lookup('env', 'DOTFILES_DIR') }}/.zshrc"
    dest: "{{ lookup('env', 'HOME') }}/.zshrc"
    state: link
    force: yes

#
# zprezto
#

- name: Install zprezto
  git:
    repo: https://github.com/sorin-ionescu/prezto.git
    dest: "{{ lookup('env', 'HOME') }}/.zprezto"
    recursive: true

- name: Create .zpreztorc link
  file:
    src: "{{ lookup('env', 'DOTFILES_DIR') }}/.zpreztorc"
    dest: "{{ lookup('env', 'HOME') }}/.zpreztorc"
    state: link
    force: yes

#
# tmux
#

- name: Install tmux
  homebrew:
    name: tmux
    state: present

- name: install tpm
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"

- name: Create .tmux.conf link
  tags:
    - tmux
  file:
    src: "{{ lookup('env', 'DOTFILES_DIR') }}/.tmux.conf"
    dest: "{{ lookup('env', 'HOME') }}/.tmux.conf"
    state: link
    force: yes
