- include_tasks: common.yml
  tags: [ common ]

- include_tasks: iterm2.yml
  tags: [ iterm2 ]

- include_tasks: emacs.yml
  tags: [ emacs ]

- include_tasks: javascript.yml
  tags: [ javascript ]

- include_tasks: java.yml
  tags: [ java ]

- include_tasks: clojure.yml
  tags: [ clojure ]

- include_tasks: docker.yml
  tags: [ docker ]

- include_tasks: apps.yml
  tags: [ apps ]
