- name: Install Docker repository dependencies
  become: yes
  become_user: root
  apt:
    update_cache: yes
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Add Docker official GPG key
  become: yes
  become_user: root
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  become: yes
  become_user: root
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install Docker
  become: yes
  become_user: root
  apt:
    update_cache: yes
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Create a docker group
  become: yes
  group:
    name: docker
    state: present

- name: Add current user to docker group
  become: yes
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: yes

- name: Ensure ~/.local/bin exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: directory

- name: Install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-Linux-x86_64"
    dest: "{{ lookup('env', 'HOME') }}/.local/bin/docker-compose"
    mode: "+x"
