- name: Set up local workstation
  hosts: local
  roles:
    - role: common
      tags:
        - common

    - role: terminal
      tags:
        - terminal

    - role: docker
      tags:
        - docker

    - role: emacs
      tags:
        - emacs

    - role: javascript
      tags:
        - javascript

    - role: java
      tags:
        - java

    - role: clojure
      tags:
        - clojure

    - role: ruby
      tags:
        - ruby

    - role: apps
      tags:
        - apps

    - role: gnome
      tags:
        - gnome

    - role: keyboard
      tags:
        - keyboard

    - role: kubernetes
      tags:
        - kubernetes
