#
# zsh
#

- name: Install zsh
  tags:
    - zsh
  become: yes
  become_user: root
  apt:
    name: zsh
    state: present

- name: Set zsh as default shell
  tags:
    - zsh
  become: yes
  become_user: root
  command: chsh -s /bin/zsh {{ lookup('env', 'USER') }}
  register: zsh_for_user
  failed_when: zsh_for_user.rc >= 1
  changed_when: zsh_for_user.rc == 0

- name: Install Base16 shell
  tags:
    - zsh
  git:
    repo: "https://github.com/chriskempson/base16-shell.git"
    dest: "{{ lookup('env', 'HOME') }}/.config/base16-shell"

- name: Create .zshrc link
  tags:
    - zsh
  file:
    src: "{{ lookup('env', 'DOTFILES_DIR') }}/.zshrc"
    dest: "{{ lookup('env', 'HOME') }}/.zshrc"
    state: link
    force: yes

#
# zprezto
#

- name: Install zprezto
  tags:
    - zprezto
  git:
    repo: https://github.com/sorin-ionescu/prezto.git
    dest: "{{ lookup('env', 'HOME') }}/.zprezto"
    recursive: true

- name: Create .zpreztorc link
  tags:
    - zprezto
  file:
    src: "{{ lookup('env', 'DOTFILES_DIR') }}/.zpreztorc"
    dest: "{{ lookup('env', 'HOME') }}/.zpreztorc"
    state: link
    force: yes

#
# tmux
#

- name: Install tmux
  tags:
    - tmux
  become: yes
  become_user: root
  apt:
    name: tmux
    state: present

- name: install tpm
  git:
    repo: "https://github.com/tmux-plugins/tpm.git"
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"

- name: Create .tmux.conf link
  tags:
    - tmux
  file:
    src: "{{ lookup('env', 'DOTFILES_DIR') }}/.tmux.conf"
    dest: "{{ lookup('env', 'HOME') }}/.tmux.conf"
    state: link
    force: yes
