- name: Install emacs packages' system dependencies
  become: yes
  become_user: root
  tags:
    - deps
  apt:
    pkg:
      # Some packages depends on build-essential tools such as `make`
      # to build from source.
      - build-essential
      # Install makeinfo for the same reason above.
      - texinfo

      # Electronic lexical database of English language.
      # Required by: wordnut
      - wordnet

# Faster recursive search using a regex patter.
# Required by: Wilfred/deadgrep
- name: Install ripgrep
  become: yes
  become_user: root
  tags:
    - deps
  apt:
    deb: https://github.com/BurntSushi/ripgrep/releases/download/12.1.1/ripgrep_12.1.1_amd64.deb

- name: Install emacs
  become: yes
  become_user: root
  apt:
    name: emacs
    state: present

- name: Create .emacs.d link
  file:
    src: "{{ lookup('env', 'DOTFILES_DIR') }}/emacs.d"
    dest: "{{ lookup('env', 'HOME') }}/.emacs.d"
    state: link
    force: yes

- name: Add emacsclient shorthand alias
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.composed-variables"
    regexp: '^alias e='
    line: "alias e='emacsclient --tty'"
