name: CI

on:
  push:
    branches: [ master, take-it-to-another-level ]
  pull_request:
    branches: [ master, take-it-to-another-level ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: docker build --tag dotfiles .

      - name: Test install playbook
        run: docker run dotfiles ansible-playbook -i ./ansible/hosts --skip-tags "apps,gnome" ./ansible/main.yml
