name: CI

on:
  push:
    branches: [ master, take-it-to-another-level ]
  pull_request:
    branches: [ master, take-it-to-another-level ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Does it have docker?
        uses: docker --version
