return {}
-- return {
--   'yetone/avante.nvim',
--   event = 'VeryLazy',
--   lazy = false,
--   version = false,
--   -- IMPORTANT: Building from source requires `cargo`. It's build from source
--   -- here to fix https://github.com/yetone/avante.nvim/issues/544
--   -- Change it to `build = 'make'`, for the default configuration.
--   build = 'make',
--   opts = {
--     debug = false,
--     provider = 'claude',
--     mode = '',
--     auto_suggestions_provider = 'claude',
--     hints = { enabled = true },
--     suggestion = {
--       debounce = 100, -- Delay before triggering (ms)
--       throttle = 100, -- Minimum time between requests (ms)
--     },
--     behaviour = {
--       auto_apply_diff_after_generation = false,
--       auto_set_highlight_group = true,
--       auto_set_keymaps = true,
--       auto_suggestions = false, -- Experimental. Not great yet
--       enable_token_counting = true,
--       minimize_diff = true, -- Remove unchanged lines when applying a code block.
--       support_paste_from_clipboard = false,
--       auto_approve_tool_permissions = false,
--       -- Examples:
--       -- auto_approve_tool_permissions = true,                -- Auto-approve all tools (no prompts)
--       -- auto_approve_tool_permissions = {"bash", "replace_in_file"}, -- Auto-approve specific tools only
--     },
--     mappings = {
--       suggestion = {
--         accept = '<C-y>',
--         next = '<C-n>',
--         prev = '<C-p>',
--         dismiss = '<C-]>',
--       },
--     },
--     windows = {
--       wrap = true,
--       width = 30,
--       sidebar_header = {
--         enabled = true,
--       },
--     },
--     providers = {
--       claude = {
--         endpoint = 'https://api.anthropic.com',
--         model = 'claude-sonnet-4-2025051',
--         -- model = 'claude-opus-4-20250514',
--         timeout = 30000,
--         disable_tools = false,
--         extra_request_body = {
--           temperature = 0,
--           max_tokens = 4096,
--         },
--       },
--     },
--   },
--   dependencies = {
--     'stevearc/dressing.nvim',
--     'nvim-lua/plenary.nvim',
--     'MunifTanjim/nui.nvim',
--     'hrsh7th/nvim-cmp',
--     'nvim-tree/nvim-web-devicons',
--     'nvim-telescope/telescope.nvim',
--     'hrsh7th/nvim-cmp',
--     'zbirenbaum/copilot.lua',
--     {
--       'HakonHarnes/img-clip.nvim',
--       event = 'VeryLazy',
--       opts = {
--         default = {
--           embed_image_as_base64 = false,
--           prompt_for_file_name = false,
--           drag_and_drop = {
--             insert_mode = true,
--           },
--         },
--       },
--     },
--     {
--       'MeanderingProgrammer/render-markdown.nvim',
--       opts = {
--         file_types = { 'markdown', 'Avante' },
--       },
--       ft = { 'markdown', 'Avante' },
--     },
--   },
-- }
